#@TYPE: Machine
#@NAME: Qualcomm IQ10-RRD based on Nord with open boot firmware support
#@DESCRIPTION: Machine configuration for Qualcomm IQ10-RRD, with Nord

require conf/machine/iq-10-rrd.conf

EXTRA_IMAGEDEPENDS += "trusted-firmware-a-qcom-nord"

MACHINE_FEATURES += "optee"
MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('BBFILE_COLLECTIONS', 'meta-arm', 'packagegroup-optee', '', d)}"

PREFERRED_PROVIDER_virtual/bootloader = "u-boot-qcom"
