# This file specifies the necessary versions for the binary recipes.

VERSION_abseil-cpp ?= "20260107.1"
PREFERRED_VERSION_abseil-cpp = "${VERSION_abseil-cpp}"
PREFERRED_VERSION_abseil-cpp-native = "${VERSION_abseil-cpp}"
PREFERRED_VERSION_nativesdk-abseil-cpp = "${VERSION_abseil-cpp}"

VERSION_protobuf ?= ""
PREFERRED_VERSION_protobuf = "${VERSION_protobuf}"
PREFERRED_VERSION_protobuf-native = "${VERSION_protobuf}"
PREFERRED_VERSION_nativesdk-protobuf = "${VERSION_protobuf}"
